### ISSUE TITLE
jstorm2.21版本启动nimbus报错：[ERROR 2017-08-12 16:50:55 c.a.j.d.n.NimbusServer:142 main] Fail to run nimbus  java.lang.UnsatisfiedLinkError: /home/storm/jstorm-2.2.1/tmp/librocksdbjni-linux64.so: /home/storm/jstorm-2.2.1/tmp/librocksdbjni-linux64.so: 无法打开共享对象文件: 没有那个文件或目录 (Possible cause: can't load AMD 64-bit .so on a Power PC 64-bit platform)

### ISSUE THREAD

**Issue by qixiaolei04** [Hack-with-Github/Awesome-Hacking#19]
power主机，openjdk、ibm的jdk都试过，报错一样，求解，急急急

[INFO 2017-08-12 16:50:55 c.a.j.b.FileBlobStoreImpl:104 main] Creating new blob store based in /home/storm/jstorm-2.2.1/data/blobs
[INFO 2017-08-12 16:50:55 c.a.j.c.DefaultWatcherCallBack:40 main-EventThread] Zookeeper state update::connected,:none,null
[INFO 2017-08-12 16:50:55 c.a.j.c.DistributedClusterState:86 main-EventThread] Received event SyncConnected:None:null
[INFO 2017-08-12 16:50:55 c.a.j.d.n.NimbusCache:72 main] NimbusCache db Cache will use com.alibaba.jstorm.cache.RocksDBCache
[ERROR 2017-08-12 16:50:55 c.a.j.d.n.NimbusServer:142 main] Fail to run nimbus 
java.lang.UnsatisfiedLinkError: /home/storm/jstorm-2.2.1/tmp/librocksdbjni-linux64.so: /home/storm/jstorm-2.2.1/tmp/librocksdbjni-linux64.so: 无法打开共享对象文件: 没有那个文件或目录 (Possible cause: can't load AMD 64-bit .so on a Power PC 64-bit platform)
	at java.lang.ClassLoader$NativeLibrary.load(Native Method) ~[na:1.8.0_65]
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1938) ~[na:1.8.0_65]
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1821) ~[na:1.8.0_65]
	at java.lang.Runtime.load0(Runtime.java:809) ~[na:1.8.0_65]
	at java.lang.System.load(System.java:1086) ~[na:1.8.0_65]
	at org.rocksdb.NativeLibraryLoader.loadLibraryFromJar(NativeLibraryLoader.java:105) ~[rocksdbjni-4.3.1.jar:na]
	at org.rocksdb.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:56) ~[rocksdbjni-4.3.1.jar:na]
	at org.rocksdb.RocksDB.loadLibrary(RocksDB.java:47) ~[rocksdbjni-4.3.1.jar:na]
	at org.rocksdb.RocksDB.<clinit>(RocksDB.java:23) ~[rocksdbjni-4.3.1.jar:na]
	at com.alibaba.jstorm.cache.RocksDBCache.<clinit>(RocksDBCache.java:39) ~[jstorm-core-2.2.1.jar:na]
	at java.lang.Class.forName0(Native Method) ~[na:1.8.0_65]
	at java.lang.Class.forName(Class.java:264) ~[na:1.8.0_65]
	at backtype.storm.utils.Utils.newInstance(Utils.java:118) ~[jstorm-core-2.2.1.jar:na]
	at com.alibaba.jstorm.daemon.nimbus.NimbusCache.<init>(NimbusCache.java:75) ~[jstorm-core-2.2.1.jar:na]
	at com.alibaba.jstorm.daemon.nimbus.NimbusData.createCache(NimbusData.java:259) ~[jstorm-core-2.2.1.jar:na]
	at com.alibaba.jstorm.daemon.nimbus.NimbusData.<init>(NimbusData.java:149) ~[jstorm-core-2.2.1.jar:na]
	at com.alibaba.jstorm.daemon.nimbus.NimbusServer.createNimbusData(NimbusServer.java:234) [jstorm-core-2.2.1.jar:na]
	at com.alibaba.jstorm.daemon.nimbus.NimbusServer.launchServer(NimbusServer.java:126) [jstorm-core-2.2.1.jar:na]
	at com.alibaba.jstorm.daemon.nimbus.NimbusServer.main(NimbusServer.java:102) [jstorm-core-2.2.1.jar:na]
[INFO 2017-08-12 16:50:55 c.a.j.d.n.NimbusServer:357 main] Notify to quit nimbus
[INFO 2017-08-12 16:50:55 c.a.j.d.n.NimbusServer:147 main] Quit nimbus
[INFO 2017-08-12 16:50:55 c.a.j.d.n.NimbusServer:357 Thread-0] Notify to quit nimbus

**Comment by elizabeththecountess666** [comment]
Thank you so very much!😂😃😉

😇

**Comment by qixiaolei04** [comment]
已找到问题了，jstrom目前只支撑SUN的jdk，ibm/openjdk都不可以，在创建临时文件时会有问题
